# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(489, 342)
        mainWindow.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_tasks = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tasks.setGeometry(QtCore.QRect(20, 20, 321, 21))
        self.lineEdit_tasks.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_tasks.setObjectName("lineEdit_tasks")
        self.pushButton_addTask = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addTask.setGeometry(QtCore.QRect(350, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_addTask.setFont(font)
        self.pushButton_addTask.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 51, 102); \n"
"border-radius: 5px;")
        self.pushButton_addTask.setObjectName("pushButton_addTask")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 451, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(160, 270, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 51, 102);\n"
"border-radius: 5px;")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_delete_all = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_all.setGeometry(QtCore.QRect(190, 300, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_delete_all.setFont(font)
        self.pushButton_delete_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 51, 102);\n"
"border-radius: 5px;")
        self.pushButton_delete_all.setObjectName("pushButton_delete_all")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "To Do List "))
        self.pushButton_addTask.setText(_translate("mainWindow", "Add Task"))
        self.pushButton_delete.setText(_translate("mainWindow", "Delete Completed Tasks"))
        self.pushButton_delete_all.setText(_translate("mainWindow", "Delete All Tasks"))
