# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(608, 737)
        mainWindow.setStyleSheet("background-color: rgb(255, 204, 204);\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_enter_tasks = QtWidgets.QLabel(self.centralwidget)
        self.label_enter_tasks.setGeometry(QtCore.QRect(110, 460, 111, 16))
        self.label_enter_tasks.setStyleSheet("font: 18pt \"Baskerville\";")
        self.label_enter_tasks.setObjectName("label_enter_tasks")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 480, 391, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 510, 281, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_addTask = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_addTask.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Papyrus\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_addTask.setObjectName("pushButton_addTask")
        self.verticalLayout.addWidget(self.pushButton_addTask)
        self.pushButton_deleteTask = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_deleteTask.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Papyrus\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_deleteTask.setObjectName("pushButton_deleteTask")
        self.verticalLayout.addWidget(self.pushButton_deleteTask)
        self.pushButton_del_all_tasks = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_del_all_tasks.setStyleSheet("color: rgb(0,0,0);\n"
"font: 14pt \"Papyrus\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_del_all_tasks.setObjectName("pushButton_del_all_tasks")
        self.verticalLayout.addWidget(self.pushButton_del_all_tasks)
        self.pushButton_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_exit.setStyleSheet("color: rgb(51, 51, 51);\n"
"font: 14pt \"Papyrus\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout.addWidget(self.pushButton_exit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 210, 61))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 102);\n"
"font: 35pt \"Papyrus\";")
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 41, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 110, 521, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.textEdit_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_3.addWidget(self.textEdit_4)
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_3.addWidget(self.textEdit_2)
        self.textEdit_6 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_3.addWidget(self.textEdit_6)
        self.textEdit_5 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_3.addWidget(self.textEdit_5)
        self.textEdit_7 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_3.addWidget(self.textEdit_7)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "To Do List "))
        self.label_enter_tasks.setText(_translate("mainWindow", "Enter the tasks:"))
        self.pushButton_addTask.setText(_translate("mainWindow", "Add Task"))
        self.pushButton_deleteTask.setText(_translate("mainWindow", "Delete Task"))
        self.pushButton_del_all_tasks.setText(_translate("mainWindow", "Delete All Tasks"))
        self.pushButton_exit.setText(_translate("mainWindow", "Exit"))
        self.label.setText(_translate("mainWindow", "TO DO LIST"))
